[package]
name = "prisma-cli"
publish = false
version = "0.0.0"
edition = "2021"

[dependencies]

[dependencies.prisma-client-rust-cli]
rev = "bb1c2d3"
default-features = false
features = ["postgresql", "migrations"]
git = "https://github.com/Brendonovich/prisma-client-rust"
