FROM node:20-alpine
WORKDIR /src
RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml ./
RUN pnpm i --frozen-lockfile

COPY . .

EXPOSE 3000
CMD ["pnpm", "dev"]
