docker_build(
	"ghcr.io/m1guelpf/dyson-frontend", ".",
	dockerfile="Dockerfile.dev",
	live_update=[
		sync('.', '/src/'),
		run('corepack pnpm install --frozen-lockfile', trigger=['./package.json', './pnpm-lock.yaml'])
	]
)

k8s_yaml('../infra/frontend.yaml')
k8s_resource(
  workload='dyson-frontend',
  port_forwards=3000
)
