apiVersion: apps/v1
kind: Deployment
metadata:
  name: dyson-frontend
  labels:
    app: dyson
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dyson
      component: frontend
  template:
    metadata:
      labels:
        app: dyson
        component: frontend
    spec:
      containers:
        - name: dyson-frontend
          image: ghcr.io/m1guelpf/dyson-frontend:edge
          env:
            - name: SESSION_SECRET
              value: UsHJUMm1RebxardLRMw2Pzhr6K+2Tmv5XEt7bHEPZ08=
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 5
