apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dyson
  name: dyson-redis-storage
  labels:
    app: dyson
    component: redis
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dyson-redis
  namespace: dyson
  labels:
    app: dyson
    components: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dyson
      component: redis
  template:
    metadata:
      labels:
        app: dyson
        component: redis
    spec:
      containers:
        - name: dyson-redis
          image: redis:latest
          ports:
            - containerPort: 6379
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          volumeMounts:
            - name: dyson-redis-storage
              mountPath: /data
      volumes:
        - name: dyson-redis-storage
          persistentVolumeClaim:
            claimName: dyson-redis-storage
---
apiVersion: v1
kind: Service
metadata:
  name: dyson-redis
  namespace: dyson
  labels:
    app: dyson
    component: redis
spec:
  selector:
    app: dyson
    component: redis
  ports:
    - protocol: TCP
      port: 6379
  type: ClusterIP
---
