---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    email: "{{CF_EMAIL}}"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cf-letsencrypt-account-key
    solvers:
      - dns01:
          cloudflare:
            email: "{{CF_EMAIL}}"
            apiTokenSecretRef:
              name: cloudflare-token
              key: api-token
