name: Frontend CI

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yaml"

jobs:
  lint:
    name: Code formatting & linting
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8.5.0
          run_install: |
            - args: [--frozen-lockfile]

      - name: Generate database types
        run: pnpm prisma generate

      - name: Check formatting with Prettier
        run: pnpm format:check

      - name: Lint
        run: pnpm lint

      - name: Check Typescript
        run: pnpm typecheck
